######################################################
#                                                    #
#            Sounds Configuration Files              #
#                                                    #
######################################################

# This is sound config version.
# PLEASE DON'T TOUCH THIS PATH IF YOU DON'T KNOW THIS!
SoundConfigVersion: 1

# Sound when players on cooldown to viewing profile via chat.
ON_COOLDOWN_COMMAND: ENTITY_VILLAGER_NO,1,1

# Sound when players viewing profile via chat.
ON_VIEW_PROFILE_CHAT: ENTITY_PLAYER_LEVELUP,1,1

# Sound when players open profile inventory.
ON_INVENTORY_OPEN: BLOCK_CHEST_OPEN,1,1

# Sound when players close profile inventory.
ON_INVENTORY_CLOSE: BLOCK_CHEST_CLOSE,1,1

# Sound when players click next page in profile inventory.
ON_INVENTORY_NEXT_PAGE: BLOCK_DISPENSER_LAUNCH,1,1

# Sound when players click previous page in profile inventory.
ON_INVENTORY_PREVIOUS_PAGE: BLOCK_DISPENSER_DISPENSE,1,1